export const COMPANY_INFO = {
  name: 'Rare Marketing',
  tagline: 'Exceptional Digital Marketing for Ambitious Brands',
  description: 'We help businesses grow through strategic digital marketing, compelling content creation, and data-driven campaigns that deliver real results.',
  email: 'hello@raremarketing.com',
  phone: '+1 (555) 123-4567',
  address: {
    street: '123 Innovation Drive',
    city: 'San Francisco',
    state: 'CA',
    zip: '94105',
    country: 'United States',
  },
  social: {
    twitter: 'https://twitter.com/raremarketing',
    linkedin: 'https://linkedin.com/company/rare-marketing',
    instagram: 'https://instagram.com/raremarketing',
    facebook: 'https://facebook.com/raremarketing',
  },
  founded: 2024,
};

export const NAVIGATION_ITEMS = [
  { name: 'Home', href: '/' },
  { name: 'About', href: '/about' },
  { name: 'Services', href: '/services' },
  { name: 'Blog', href: '/blog' },
  { name: 'Contact', href: '/contact' },
];

export const SERVICES = [
  {
    id: 'content-creation',
    name: 'Content Creation',
    shortDescription: 'Compelling content that converts',
    description: 'From blog posts to video scripts, we create content that resonates with your audience and drives engagement.',
    features: [
      'Blog writing & SEO optimization',
      'Social media content',
      'Video scripts & storyboards',
      'Email marketing campaigns',
      'Website copy & landing pages',
      'Brand storytelling',
    ],
    pricing: {
      starter: {
        name: 'Starter',
        price: 1500,
        period: 'month',
        features: [
          '8 blog posts per month',
          '20 social media posts',
          'Basic SEO optimization',
          'Content calendar',
          'Email support',
        ],
      },
      professional: {
        name: 'Professional',
        price: 2500,
        period: 'month',
        features: [
          '12 blog posts per month',
          '40 social media posts',
          'Advanced SEO optimization',
          'Video script writing',
          'Email campaigns',
          'Priority support',
        ],
        popular: true,
      },
      enterprise: {
        name: 'Enterprise',
        price: 4000,
        period: 'month',
        features: [
          'Unlimited blog posts',
          'Unlimited social content',
          'Full content strategy',
          'Video production support',
          'Brand storytelling',
          'Dedicated account manager',
        ],
      },
    },
  },
  {
    id: 'social-media-management',
    name: 'Social Media Management',
    shortDescription: 'Build your brand presence',
    description: 'Strategic social media management that builds communities, drives engagement, and grows your brand.',
    features: [
      'Multi-platform management',
      'Content creation & scheduling',
      'Community engagement',
      'Analytics & reporting',
      'Influencer partnerships',
      'Paid social advertising',
    ],
    pricing: {
      starter: {
        name: 'Starter',
        price: 1200,
        period: 'month',
        features: [
          '2 social platforms',
          '15 posts per month',
          'Basic analytics',
          'Community management',
          'Email support',
        ],
      },
      professional: {
        name: 'Professional',
        price: 2000,
        period: 'month',
        features: [
          '4 social platforms',
          '30 posts per month',
          'Advanced analytics',
          'Influencer outreach',
          'Paid ad management',
          'Priority support',
        ],
        popular: true,
      },
      enterprise: {
        name: 'Enterprise',
        price: 3500,
        period: 'month',
        features: [
          'All major platforms',
          'Unlimited posts',
          'Custom reporting',
          'Crisis management',
          'Full ad campaign management',
          'Dedicated account manager',
        ],
      },
    },
  },
  {
    id: 'seo-optimization',
    name: 'SEO Optimization',
    shortDescription: 'Dominate search results',
    description: 'Comprehensive SEO strategies that improve your search rankings and drive organic traffic.',
    features: [
      'Technical SEO audits',
      'Keyword research & strategy',
      'On-page optimization',
      'Link building campaigns',
      'Local SEO optimization',
      'Performance tracking',
    ],
    pricing: {
      starter: {
        name: 'Starter',
        price: 1800,
        period: 'month',
        features: [
          'SEO audit & strategy',
          'Keyword research',
          'On-page optimization',
          'Monthly reporting',
          'Email support',
        ],
      },
      professional: {
        name: 'Professional',
        price: 3000,
        period: 'month',
        features: [
          'Comprehensive SEO strategy',
          'Technical optimization',
          'Link building campaign',
          'Local SEO setup',
          'Bi-weekly reporting',
          'Priority support',
        ],
        popular: true,
      },
      enterprise: {
        name: 'Enterprise',
        price: 5000,
        period: 'month',
        features: [
          'Enterprise SEO strategy',
          'Advanced technical SEO',
          'Aggressive link building',
          'Multi-location optimization',
          'Weekly reporting',
          'Dedicated SEO specialist',
        ],
      },
    },
  },
  {
    id: 'digital-marketing',
    name: 'Digital Marketing',
    shortDescription: 'Complete marketing solutions',
    description: 'Full-service digital marketing campaigns that integrate all channels for maximum impact.',
    features: [
      'Paid advertising (Google, Facebook, LinkedIn)',
      'Email marketing automation',
      'Conversion rate optimization',
      'Marketing analytics',
      'Customer journey mapping',
      'Growth strategy consulting',
    ],
    pricing: {
      starter: {
        name: 'Starter',
        price: 2500,
        period: 'month',
        features: [
          'Google Ads management',
          'Basic email campaigns',
          'Landing page optimization',
          'Monthly reporting',
          'Email support',
        ],
      },
      professional: {
        name: 'Professional',
        price: 4000,
        period: 'month',
        features: [
          'Multi-platform ad management',
          'Advanced email automation',
          'A/B testing & optimization',
          'Customer journey mapping',
          'Bi-weekly reporting',
          'Priority support',
        ],
        popular: true,
      },
      enterprise: {
        name: 'Enterprise',
        price: 7500,
        period: 'month',
        features: [
          'Full-funnel marketing strategy',
          'Advanced automation',
          'Custom analytics dashboard',
          'Growth strategy consulting',
          'Weekly strategy calls',
          'Dedicated marketing team',
        ],
      },
    },
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Sarah Johnson',
    company: 'TechStart Inc.',
    role: 'CEO',
    content: 'Rare Marketing transformed our digital presence. Their strategic approach and creative content helped us increase leads by 300% in just 6 months.',
    rating: 5,
    image: '/testimonials/sarah-johnson.jpg',
  },
  {
    id: 2,
    name: 'Michael Chen',
    company: 'GrowthCo',
    role: 'Marketing Director',
    content: 'Working with Rare Marketing has been a game-changer. Their SEO expertise helped us rank #1 for our target keywords, driving significant organic growth.',
    rating: 5,
    image: '/testimonials/michael-chen.jpg',
  },
  {
    id: 3,
    name: 'Emily Rodriguez',
    company: 'Local Boutique',
    role: 'Owner',
    content: 'As a small business, we needed cost-effective marketing that delivers results. Rare Marketing exceeded our expectations and helped us double our revenue.',
    rating: 5,
    image: '/testimonials/emily-rodriguez.jpg',
  },
];

export const TEAM_MEMBERS = [
  {
    id: 1,
    name: 'Alex Thompson',
    role: 'Founder & CEO',
    bio: 'Former digital marketing director at Fortune 500 companies with 10+ years of experience driving growth for brands across industries.',
    image: '/team/alex-thompson.jpg',
    social: {
      linkedin: 'https://linkedin.com/in/alexthompson',
      twitter: 'https://twitter.com/alexthompson',
    },
  },
  {
    id: 2,
    name: 'Jessica Park',
    role: 'Creative Director',
    bio: 'Award-winning creative professional specializing in brand storytelling and content strategy that resonates with target audiences.',
    image: '/team/jessica-park.jpg',
    social: {
      linkedin: 'https://linkedin.com/in/jessicapark',
      instagram: 'https://instagram.com/jessicapark',
    },
  },
  {
    id: 3,
    name: 'David Kim',
    role: 'SEO Specialist',
    bio: 'Technical SEO expert with a track record of improving search rankings for businesses of all sizes across competitive industries.',
    image: '/team/david-kim.jpg',
    social: {
      linkedin: 'https://linkedin.com/in/davidkim',
      twitter: 'https://twitter.com/davidkim',
    },
  },
];
